name: workflow

on:
    push:
        branches:
            - master
        path-ignore:
            - 'README.md'

jobs:
    integration:
        namme: Continuous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Lint code
              run: echo "Linting repository"
            
            - name: Run unit tests
              run: echo "Running unit tests"